export const countries = [
  {
    code: "gb", name: "United Kingdom", nameAr: "المملكة المتحدة", nameFr: "Royaume-Uni",
    currency: "GBP", symbol: "£", flag: "🇬🇧",
    cities: ["Birmingham", "Nottingham", "Derby", "London", "Manchester", "Leeds", "Leicester", "Coventry"],
  },
  {
    code: "ma", name: "Morocco", nameAr: "المغرب", nameFr: "Maroc",
    currency: "MAD", symbol: "MAD", flag: "🇲🇦",
    cities: ["Casablanca", "Marrakech", "Rabat", "Tangier", "Fes", "Agadir", "Meknes", "Oujda"],
  },
  {
    code: "eg", name: "Egypt", nameAr: "مصر", nameFr: "Égypte",
    currency: "EGP", symbol: "EGP", flag: "🇪🇬",
    cities: ["Cairo", "Alexandria", "Giza", "Sharm El Sheikh", "Hurghada", "Luxor", "Mansoura", "Tanta"],
  },
  {
    code: "ae", name: "UAE", nameAr: "الإمارات", nameFr: "EAU",
    currency: "AED", symbol: "AED", flag: "🇦🇪",
    cities: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah", "Fujairah"],
  },
  {
    code: "sa", name: "Saudi Arabia", nameAr: "السعودية", nameFr: "Arabie Saoudite",
    currency: "SAR", symbol: "SAR", flag: "🇸🇦",
    cities: ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar"],
  },
  {
    code: "kw", name: "Kuwait", nameAr: "الكويت", nameFr: "Koweït",
    currency: "KWD", symbol: "KWD", flag: "🇰🇼",
    cities: ["Kuwait City", "Hawalli", "Salmiya", "Jahra"],
  },
  {
    code: "bh", name: "Bahrain", nameAr: "البحرين", nameFr: "Bahreïn",
    currency: "BHD", symbol: "BHD", flag: "🇧🇭",
    cities: ["Manama", "Muharraq", "Riffa", "Hamad Town"],
  },
  {
    code: "qa", name: "Qatar", nameAr: "قطر", nameFr: "Qatar",
    currency: "QAR", symbol: "QAR", flag: "🇶🇦",
    cities: ["Doha", "Al Wakrah", "Al Khor", "Lusail"],
  },
  {
    code: "om", name: "Oman", nameAr: "عُمان", nameFr: "Oman",
    currency: "OMR", symbol: "OMR", flag: "🇴🇲",
    cities: ["Muscat", "Salalah", "Sohar", "Nizwa"],
  },
  {
    code: "jo", name: "Jordan", nameAr: "الأردن", nameFr: "Jordanie",
    currency: "JOD", symbol: "JOD", flag: "🇯🇴",
    cities: ["Amman", "Irbid", "Zarqa", "Aqaba"],
  },
];

export const propertyTypes = ["Room", "Studio", "Flat", "Apartment", "House", "Villa", "Penthouse", "Land", "Commercial"];

export const features = [
  "Parking", "Garden", "Pool", "Gym", "Balcony", "Terrace", "Sea view", "City view",
  "Pets OK", "Bills included", "En-suite", "Washing machine", "Dishwasher",
  "Air conditioning", "Central heating", "Elevator", "Security", "Doorman",
  "Furnished", "Part furnished", "Unfurnished", "EPC C+", "Near transport",
  "Near school", "Near mosque", "Near beach", "Maid's room", "Driver's room",
];

export type Lang = "en" | "ar" | "fr";

export const translations: Record<Lang, Record<string, string>> = {
  en: {
    "hero.title": "Find your place",
    "hero.subtitle": "Rooms, flats, houses, and villas across the UK, Middle East, and North Africa. List free. Browse free. No agents needed.",
    "hero.search": "Search by city, area, or keyword...",
    "hero.cta": "Search",
    "nav.browse": "Browse",
    "nav.rooms": "Rooms",
    "nav.list": "List free",
    "nav.how": "How it works",
    "nav.login": "Log in",
    "nav.signup": "Sign up free",
    "nav.dashboard": "Dashboard",
    "listing.available": "Available now",
    "listing.perMonth": "/mo",
    "listing.beds": "beds",
    "listing.bed": "bed",
    "listing.studio": "Studio",
    "listing.interested": "Interested?",
    "listing.contact": "Contact the landlord directly — no agents, no fees.",
    "listing.whatsapp": "WhatsApp",
    "listing.sendEnquiry": "Send enquiry",
    "listing.save": "Save listing",
    "listing.saved": "Saved",
    "listing.share": "Share",
    "listing.loginToEnquire": "Log in to send an enquiry or save this listing",
    "listing.about": "About this property",
    "listing.features": "Features",
    "listing.listedBy": "Listed by",
    "list.title": "List your property",
    "list.subtitle": "Your listing goes live after review. Photos required.",
    "list.whatListing": "What are you listing?",
    "list.photos": "Photos (minimum 3 required)",
    "list.photosHint": "Upload at least 3 clear photos. Listings without quality photos won't be approved.",
    "list.video": "Video tour (optional)",
    "list.publish": "Submit for review",
    "list.signinRequired": "Sign in to list your property",
    "cta.listFree": "List for free",
    "cta.browse": "Browse listings",
    "filter.all": "All",
    "filter.allCities": "All cities",
    "filter.allCountries": "All countries",
    "filter.results": "results",
    "stats.listings": "listings live",
    "stats.countries": "countries",
    "stats.free": "Free forever",
    "stats.noFees": "Zero agent fees",
    "how.title": "How Makan works",
    "how.browse.title": "Browse or search",
    "how.browse.desc": "Filter by type, city, or budget. Every listing is free to view.",
    "how.message.title": "Message directly",
    "how.message.desc": "Contact the landlord via WhatsApp or enquiry. No middlemen.",
    "how.movein.title": "Move in",
    "how.movein.desc": "Agree terms, sign up, and move in. It's your place.",
    "footer.tagline": "Find your place. Free property listings worldwide.",
    "footer.copyright": "Makan by PropertyVault UK. Free for everyone.",
  },
  ar: {
    "hero.title": "لاقي مكانك",
    "hero.subtitle": "غرف، شقق، بيوت، وفلل في بريطانيا، الشرق الأوسط، وشمال أفريقيا. سجّل مجاناً. تصفّح مجاناً. بدون وسطاء.",
    "hero.search": "ابحث بالمدينة أو المنطقة...",
    "hero.cta": "بحث",
    "nav.browse": "تصفّح",
    "nav.rooms": "غرف",
    "nav.list": "أعلن مجاناً",
    "nav.how": "كيف يعمل",
    "nav.login": "تسجيل دخول",
    "nav.signup": "حساب جديد",
    "nav.dashboard": "لوحة التحكم",
    "listing.available": "متاح الآن",
    "listing.perMonth": "/شهر",
    "listing.beds": "غرف نوم",
    "listing.bed": "غرفة نوم",
    "listing.studio": "ستوديو",
    "listing.interested": "مهتم؟",
    "listing.contact": "تواصل مع المالك مباشرة — بدون وسطاء، بدون رسوم.",
    "listing.whatsapp": "واتساب",
    "listing.sendEnquiry": "إرسال استفسار",
    "listing.save": "حفظ",
    "listing.saved": "محفوظ",
    "listing.share": "مشاركة",
    "listing.loginToEnquire": "سجّل دخولك لإرسال استفسار أو حفظ الإعلان",
    "listing.about": "عن هذا العقار",
    "listing.features": "المميزات",
    "listing.listedBy": "بواسطة",
    "list.title": "أعلن عن عقارك",
    "list.subtitle": "إعلانك يظهر بعد المراجعة. الصور مطلوبة.",
    "list.whatListing": "ماذا تريد أن تعلن؟",
    "list.photos": "صور (٣ على الأقل)",
    "list.photosHint": "ارفع ٣ صور واضحة على الأقل. الإعلانات بدون صور جيدة لن تُقبل.",
    "list.video": "فيديو جولة (اختياري)",
    "list.publish": "إرسال للمراجعة",
    "list.signinRequired": "سجّل دخولك لإضافة عقارك",
    "cta.listFree": "أعلن مجاناً",
    "cta.browse": "تصفّح الإعلانات",
    "filter.all": "الكل",
    "filter.allCities": "كل المدن",
    "filter.allCountries": "كل الدول",
    "filter.results": "نتيجة",
    "stats.listings": "إعلان",
    "stats.countries": "دول",
    "stats.free": "مجاني للأبد",
    "stats.noFees": "بدون عمولة",
    "how.title": "كيف يعمل مكان",
    "how.browse.title": "تصفّح أو ابحث",
    "how.browse.desc": "فلتر حسب النوع أو المدينة أو الميزانية. كل الإعلانات مجانية.",
    "how.message.title": "تواصل مباشرة",
    "how.message.desc": "راسل المالك عبر واتساب أو النموذج. بدون وسطاء.",
    "how.movein.title": "انتقل",
    "how.movein.desc": "اتفق على الشروط واسكن. مكانك أنت.",
    "footer.tagline": "لاقي مكانك. إعلانات عقارية مجانية حول العالم.",
    "footer.copyright": "مكان من PropertyVault UK. مجاني للجميع.",
  },
  fr: {
    "hero.title": "Trouvez votre place",
    "hero.subtitle": "Chambres, appartements, maisons et villas au Royaume-Uni, au Moyen-Orient et en Afrique du Nord. Annoncez gratuitement. Parcourez gratuitement. Sans agents.",
    "hero.search": "Rechercher par ville, quartier ou mot-clé...",
    "hero.cta": "Rechercher",
    "nav.browse": "Parcourir",
    "nav.rooms": "Chambres",
    "nav.list": "Publier gratuit",
    "nav.how": "Comment ça marche",
    "nav.login": "Connexion",
    "nav.signup": "Inscription gratuite",
    "nav.dashboard": "Tableau de bord",
    "listing.available": "Disponible maintenant",
    "listing.perMonth": "/mois",
    "listing.beds": "chambres",
    "listing.bed": "chambre",
    "listing.studio": "Studio",
    "listing.interested": "Intéressé ?",
    "listing.contact": "Contactez le propriétaire directement — sans agents, sans frais.",
    "listing.whatsapp": "WhatsApp",
    "listing.sendEnquiry": "Envoyer une demande",
    "listing.save": "Sauvegarder",
    "listing.saved": "Sauvegardé",
    "listing.share": "Partager",
    "listing.loginToEnquire": "Connectez-vous pour envoyer une demande ou sauvegarder cette annonce",
    "listing.about": "À propos de ce bien",
    "listing.features": "Caractéristiques",
    "listing.listedBy": "Publié par",
    "list.title": "Publiez votre bien",
    "list.subtitle": "Votre annonce sera en ligne après vérification. Photos requises.",
    "list.whatListing": "Que souhaitez-vous publier ?",
    "list.photos": "Photos (minimum 3 requises)",
    "list.photosHint": "Téléchargez au moins 3 photos claires. Les annonces sans photos de qualité ne seront pas approuvées.",
    "list.video": "Visite vidéo (optionnel)",
    "list.publish": "Soumettre pour vérification",
    "list.signinRequired": "Connectez-vous pour publier votre bien",
    "cta.listFree": "Publier gratuitement",
    "cta.browse": "Parcourir les annonces",
    "filter.all": "Tout",
    "filter.allCities": "Toutes les villes",
    "filter.allCountries": "Tous les pays",
    "filter.results": "résultats",
    "stats.listings": "annonces en ligne",
    "stats.countries": "pays",
    "stats.free": "Gratuit pour toujours",
    "stats.noFees": "Zéro frais d'agence",
    "how.title": "Comment fonctionne Makan",
    "how.browse.title": "Parcourez ou recherchez",
    "how.browse.desc": "Filtrez par type, ville ou budget. Toutes les annonces sont gratuites.",
    "how.message.title": "Contactez directement",
    "how.message.desc": "Contactez le propriétaire par WhatsApp ou formulaire. Sans intermédiaires.",
    "how.movein.title": "Emménagez",
    "how.movein.desc": "Convenez des termes et emménagez. C'est votre place.",
    "footer.tagline": "Trouvez votre place. Annonces immobilières gratuites dans le monde entier.",
    "footer.copyright": "Makan par PropertyVault UK. Gratuit pour tous.",
  },
};

export function getCountry(code: string) {
  return countries.find(c => c.code === code);
}

export function getCities(countryCode: string) {
  return getCountry(countryCode)?.cities || [];
}

export function formatPrice(amount: number, countryCode: string) {
  const country = getCountry(countryCode);
  if (!country) return `${amount}`;
  if (country.currency === "GBP") return `£${amount.toLocaleString()}`;
  return `${amount.toLocaleString()} ${country.symbol}`;
}
