import { CALENDAR, fullCaption, type ReelSpec } from "../reel-calendar";
import { canonical } from "../site";
import type { NewPost } from "./db";
import { addDays, isYmd } from "./dates";

/**
 * Turning the calendar into queue rows.
 *
 * The thirty Reels are still generated by lib/reel-calendar.ts; what changes
 * is that they are copied into social_posts once, dated from a chosen start,
 * and from then on the queue is the truth. Re-running the seed after a day
 * has been published, held or skipped must not touch it — the digest is what
 * makes the seed idempotent, and the script skips anything already present.
 *
 * Pure: the file digests come in as a function so the test can run without
 * the thirty videos.
 */

export const CALCULATORS = ["tax.ts", "finance.ts", "deal-score.ts"] as const;

export function fileNameFor(spec: ReelSpec): string {
  return `day-${String(spec.day).padStart(2, "0")}-${spec.id}.mp4`;
}

export function calendarRows(opts: {
  startDate: string;
  sha256Of: (fileName: string) => string;
  channel?: string;
}): NewPost[] {
  if (!isYmd(opts.startDate)) throw new Error(`start date must be YYYY-MM-DD, got "${opts.startDate}"`);
  const channel = opts.channel ?? "instagram";

  return CALENDAR.map(spec => {
    const file = fileNameFor(spec);
    return {
      channel,
      slot_date: addDays(opts.startDate, spec.day - 1),
      format: spec.format,
      asset_url: canonical(`/reels/${file}`),
      asset_sha256: opts.sha256Of(file),
      caption: fullCaption(spec),
      status: "queued",
      evergreen: false,
      source_refs: { calendarId: spec.id, day: spec.day, calculators: [...CALCULATORS] },
    };
  });
}

/** Pool copies of chosen calendar days. No date, evergreen, same content. */
export function evergreenRows(opts: {
  days: number[];
  sha256Of: (fileName: string) => string;
  channel?: string;
}): NewPost[] {
  const channel = opts.channel ?? "instagram";
  return opts.days.map(day => {
    const spec = CALENDAR.find(r => r.day === day);
    if (!spec) throw new Error(`no calendar day ${day}; the calendar runs 1-${CALENDAR.length}`);
    const file = fileNameFor(spec);
    return {
      channel,
      slot_date: null,
      format: spec.format,
      asset_url: canonical(`/reels/${file}`),
      asset_sha256: opts.sha256Of(file),
      caption: fullCaption(spec),
      status: "queued",
      evergreen: true,
      source_refs: { calendarId: spec.id, day: spec.day, calculators: [...CALCULATORS] },
    };
  });
}

/** "3,7,12" → [3, 7, 12]. Refuses anything that is not a whole number. */
export function parseDays(arg: string): number[] {
  return arg.split(",").map(s => s.trim()).filter(Boolean).map(s => {
    const n = Number(s);
    if (!Number.isInteger(n) || n < 1) throw new Error(`not a day number: "${s}"`);
    return n;
  });
}
